### ISSUE TITLE
Incompatibility with for-of loose mode

### ISSUE THREAD

**Issue by STRML** [MatAtBread/nodent#67] opened 2016-10-24 23:58 UTC
`for-of` in loose mode generates code that is incorrectly compiled by nodent.

This is a continuation of https://github.com/MatAtBread/fast-async/issues/22.

Here's [an example on the Nodent site](http://nodent.mailed.me.uk/#%2F%2FES7%20code%0Aasync%20function%20run(languages)%20%7B%0A%20%20const%20fileContents%20%3D%20await%20readFileAsync(filePath%2C%20'utf8')%3B%0A%20%20for%20(var%20_iterator%20%3D%20fileContents%2C%20_isArray%20%3D%20Array.isArray(_iterator)%2C%20_i%20%3D%200%2C%20_iterator%20%3D%20_isArray%20%3F%20_iterator%20%3A%20_iterator%5BSymbol.iterator%5D()%3B%3B)%20%7B%0A%20%20%20%20var%20_ref%3B%0A%0A%20%20%20%20if%20(_isArray)%20%7B%0A%20%20%20%20%20%20if%20(_i%20%3E%3D%20_iterator.length)%20break%3B%0A%20%20%20%20%20%20_ref%20%3D%20_iterator%5B_i%2B%2B%5D%3B%0A%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20_i%20%3D%20_iterator.next()%3B%0A%20%20%20%20%20%20if%20(_i.done)%20break%3B%0A%20%20%20%20%20%20_ref%20%3D%20_i.value%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20const%20field%20%3D%20_ref%3B%0A%20%20%7D%0A%7D).

The offending code:

```jsx
for ({
    _iterator = fileContents
    _isArray = Array.isArray(_iterator)
    _i = 0
    _iterator = _isArray ? _iterator : _iterator[Symbol.iterator]()
}; ; ) {
```

which comes from:

```jsx
  for (var _iterator = fileContents, _isArray = Array.isArray(_iterator), _i = 0, _iterator = _isArray ? _iterator : _iterator[Symbol.iterator]();;) {
```

**Comment by STRML** [comment] 2016-10-25 00:18
Here's a more [minimal example](http://nodent.mailed.me.uk/#%2F%2FES7%20code%0Aasync%20function%20run()%20%7B%0A%20%20await%20foo()%3B%0A%20%20for%20(var%20a%20%3D%201%2C%20b%20%3D%202%3B%20%3B)%20%7B%0A%20%20%20%20var%20_ref%3B%0A%20%20%7D%0A%7D).

**Comment by MatAtBread** [comment] 2016-10-25 09:08
Just so I understand the issue (I'll take a look at fixing it later), the problem is it doesn't compile or executes incorrectly? Just in fast-async or nodent as well?

**Comment by MatAtBread** [comment] 2016-10-25 10:09
Ok, I see it. Definitely a bug. I'll patch it and re-publish

**Comment by MatAtBread** [comment] 2016-10-25 10:51
Closed by 288016922b70595d6aa2f6a2e9e5716db008eebc.

Feel free to re-open if this doesn't address the issue you came across

**Closed by MatAtBread** 2016-10-25 10:51 UTC

**Comment by STRML** [comment] 2016-10-25 14:23
Thanks, this looks good! I appreciate the fast fix.

**Comment by MatAtBread** [comment] 2016-10-25 17:29
NP - thanks for the report
